<?xml version='1.0' encoding='UTF-8' ?>
<testsuites>
  <testsuite errors="0" failures="1" name="com.cardinal.jenkinsproject.test.UtilsTest" package="com.cardinal.jenkinsproject.test" tests="3" time="0.075" timestamp="2012-11-05T11:04:53">
    <testcase classname="com.cardinal.jenkinsproject.test.UtilsTest" name="testAndroidTestCaseSetupProperly" time="0.037" />
    <testcase classname="com.cardinal.jenkinsproject.test.UtilsTest" name="testUtilsDummyTestFail" time="0.034">
      <failure>junit.framework.AssertionFailedError: expected:&lt;2&gt; but was:&lt;1&gt;
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:282)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:201)
	at junit.framework.Assert.assertEquals(Assert.java:207)
	at com.cardinal.jenkinsproject.test.UtilsTest.testUtilsDummyTestFail(UtilsTest.java:26)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:529)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1448)
</failure>
    </testcase>
    <testcase classname="com.cardinal.jenkinsproject.test.UtilsTest" name="testUtilsDummyTestPass" time="0.004" />
    <properties />
    <system-out />
    <system-err />
  </testsuite>
</testsuites>